const uuid =require('uuid')
const yourNames =[{
    name: 'Agu',
    attitude: 'drunkard & peaceful',
    height: 'Average height',
    weight: 'fat',
    age: '30',
    status: 'married',
    state: 'ebonyi',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},

    {name: 'uchenna',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: '30',
    status: 'single',
    state: 'imo',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Raymond',
    attitude: 'Always positive and hopeful',
    height: 'Average height',
    weight: 'fat',
    age: 'below 30',
    status: 'single',
    state: 'imo',
    vision: 'hopeful and focus',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'John',
    attitude: 'Always mindful of masters',
    height: 'Average height',
    weight: 'slim',
    age: '20 and up',
    status: 'single',
    state: 'imo',
    vision: 'great thinker and visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Jerry',
    attitude: 'Always positive',
    height: 'Average height',
    weight: 'slim',
    age: 'plus 30',
    status: 'always late mingling',
    state: 'any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Chris',
    attitude: 'Always happy and positive',
    height: 'tall',
    weight: 'slim',
    age: '20 plus',
    status: 'loves mingling well',
    state: 'any state',
    vision: 'Hopeful and sees ahead',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Sunny',
    attitude: 'Always lovely and positive',
    height: 'Average height',
    weight: 'slim',
    age: '40 below',
    status: 'single',
    state: 'America',
    vision: 'visionary',
    sexuality: 'gay',
    id: uuid.v4(),
},
{name: 'Joe',
    attitude: 'Always positive',
    height: 'tall',
    weight: 'fat',
    age: 'plus 30',
    status: 'single',
    state: 'Asian',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Godwin',
    attitude: 'Always positive and annoying',
    height: 'Average height',
    weight: 'fat',
    age: '30',
    status: 'single',
    state: 'any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Obinna',
    attitude: 'Always positive and caring',
    height: 'Average height',
    weight: 'slim',
    age: 'above 30',
    status: 'single',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},

{name: 'Tochi',
    attitude: 'Always positive, caring and loving',
    height: 'tall in height',
    weight: 'Good body',
    age: 'above 30',
    status: 'single',
    state: 'Any state',
    vision: 'poised and visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},

{name: 'chibuzo',
attitude: 'Kind and secretive',
height: 'Average height',
weight: 'fat',
age: 'above 30',
status: 'always wants enjoyment',
state: 'imo',
vision: 'visionary',
sexuality: 'straight',
id: uuid.v4(),
},
{name: 'Ebuka',
attitude: 'positive and aggressive',
height: 'Average height',
weight: 'slim',
age: 'below 30',
status: 'single',
state: 'Any state',
vision: 'visionary',
sexuality: 'straight',
id: uuid.v4(),
},
{   name: 'chinenye',
    attitude: 'smart and corner corner',
    height: 'Average height',
    weight: 'slim',
    age: '30 below',
    status: 'single',
    state: 'Any state',
    vision: 'Good vision and mission!',
    sexuality: 'straight',
    id: uuid.v4(),
},

    {name: 'chinedu',
    attitude: 'loves women',
    height: 'Average height',
    weight: 'huge',
    age: '35',
    status: 'married',
    state: 'Rivers',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},

    {name: 'Emeka',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'fat',
    age: '38',
    status: 'single',
    state: 'imo',
    vision: 'visionary',
    sexuality: 'gay',
    id:uuid.v4(),
},
{name: 'Okpai',
    attitude: 'Alway positive',
    height: 'Normal height',
    weight: 'slim',
    age: 'above 38',
    status: 'single',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'sraight',
    id:uuid.v4(),
},
{name: 'Uzo',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: '40',
    status: 'single',
    state: 'Enugu',
    vision: 'visionary',
    sexuality: 'undecided',
    id:uuid.v4(),
},
{name: 'ozumba',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'fat',
    age: '25',
    status: 'single',
    state: 'imo',
    vision: 'visionary',
    sexuality: 'straight',
    id:uuid.v4(),
},
{name: 'Ekene',
    attitude: 'Quiet and alway positive',
    height: 'Very tall',
    weight: 'normal',
    age: 'above 40',
    status: 'single',
    state: 'any state',
    vision: 'visionary',
    sexuality: 'straight',
    id:uuid.v4(),
},
{name: 'chizaram',
    attitude: 'Alway indoors and lazy',
    height: 'Average height',
    weight: 'normal',
    age: 'above 20',
    status: 'single',
    state: 'Any state',
    vision: 'sad often',
    sexuality: 'normal',
    id:uuid.v4(),
},
{name: 'Ogadimma',
    attitude: 'Shy and secretive',
    height: 'Tall in height',
    weight: 'fat',
    age: 'below 38',
    status: 'single',
    state: 'imo',
    vision: 'visionary',
    sexuality: 'straight',
    id:uuid.v4(),
},
{name: 'Nwadike',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'fat',
    age: ' below 38',
    status: 'single',
    state: 'Rivers',
    vision: 'visionary',
    sexuality: 'undecided',
    id:uuid.v4(),
},
{name: 'Kanu',
    attitude: 'Determined, outspoken and alway positive',
    height: 'Average height',
    weight: 'slim',
    age: 'above 20',
    status: 'single',
    state: 'any state',
    vision: 'visionary',
    sexuality: 'Normal',
    id:uuid.v4(),
},
{name: 'Eze',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'fat',
    age: 'above 40',
    status: 'marrys on time',
    state: 'Delta',
    vision: 'visionary',
    sexuality: 'straight',
    id:uuid.v4(),
},
{name: 'Ibe',
    attitude: 'very and kind positive',
    height: 'Average height',
    weight: 'slim',
    age: 'above 30',
    status: 'settles on time',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id:uuid.v4(),
},
{name: 'chisom',
    attitude: 'flexible and talkative',
    height: 'Average height',
    weight: 'fat',
    age: 'above 38',
    status: 'single',
    state: 'imo',
    vision: 'focused and poised',
    sexuality: 'undecided',
    id:uuid.v4(),
},

{name: 'Ikedinachukwu',
attitude: 'Alway positive',
height: 'Normal Height',
weight: 'slim',
age: '38',
status: 'single',
state: 'imo',
vision: 'visionary',
sexuality: 'straight',
id:uuid.v4(),
},

{name: 'Adamma',
attitude: 'confused sometimes',
height: 'Average height',
weight: 'normal body',
age: '40',
status: 'never marry in time',
state: 'imo',
vision: 'visionary',
sexuality: 'striaght',
id: uuid.v4(),
},

{name: 'Chidiebere',
attitude: 'Alway positive',
height: 'Average height',
weight: 'Good body',
age: '38',
status: 'single',
state: 'Abia',
vision: 'visionary',
sexuality: 'straight',
id: uuid.v4(),
},

{name: 'Ego',
attitude: 'jealouse',
height: 'Average height',
weight: 'fat',
age: '38',
status: 'Never settles on time',
state: 'Anambra',
vision: 'not focus',
sexuality: 'normal character',
id:uuid.v4(),
},

{name: 'Ogechi',
attitude: 'Desperate individual',
height: 'short in height',
weight: 'fat',
age: '38',
status: 'Married',
state: 'Abia',
vision: 'visionary',
sexuality: 'gay',
id: uuid.v4(),
},
{name: 'Chimaobi',
    attitude: 'Alway positive',
    height: 'short',
    weight: 'Good body',
    age: 'above 20',
    status: 'enjoys mutiple relationships',
    state: 'Any state',
    vision: 'Poised and determined',
    sexuality: 'straight',
    id: uuid.v4(),
},

{name: 'Kalu',
    attitude: 'Ambitious and dangerous',
    height: 'Good height',
    weight: 'slim',
    age: 'Above 20',
    status: 'Always mingling',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},

{name: 'Obianuju',
    attitude: 'Alway quarelling',
    height: 'Average height',
    weight: 'slim',
    age: '18 and above',
    status: 'single',
    state: 'Ebonyi',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Adindu',
    attitude: 'Pessimistic and loving',
    height: 'Average height',
    weight: 'fat',
    age: '30',
    status: 'single',
    state: 'imo',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Osinachi',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: 'Above 20',
    status: 'Unlucky mingling',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Achuzie',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: ' above 30',
    status: 'single',
    state: 'Delta',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Chikadibia',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: '22 and above',
    status: 'single',
    state: 'imo',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Edochie',
    attitude: 'Alway positive and wise',
    height: 'Good height',
    weight: 'fat',
    age: 'above 40',
    status: 'settling on time',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Duru',
    attitude: 'Belives in customs and mores a lot',
    height: 'Average height',
    weight: 'slim',
    age: 'below 40',
    status: 'single',
    state: 'imo',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Obiageri',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: '20 plus',
    status: 'Always hiding from mingling',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Onyewuchi',
    attitude: 'Alway positive',
    height: 'Good height',
    weight: 'slim',
    age: 'above 30',
    status: 'single',
    state: 'Any state',
    vision: 'positive',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Onyebuchi',
    attitude: 'Alway positive',
    height: 'Short in height',
    weight: 'fat',
    age: ' below 30',
    status: 'single',
    state: 'imo',
    vision: 'Sees tommorrow',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Chika',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: 'above 30',
    status: 'Lucky in mingling',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Ndudiri',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: 'below 30',
    status: 'single',
    state: 'Any state',
    vision: 'Hard working',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'chibueze',
    attitude: 'Unpredictable and always loud',
    height: 'Bad height',
    weight: 'Good body',
    age: 'Any age',
    status: 'Lucky in marriage',
    state: 'Essentially Imo but any state too',
    vision: 'Determined and hopeful',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Kelechi',
    attitude: 'hot-tempered and positive',
    height: 'Good height',
    weight: 'Good body',
    age: 'Any age',
    status: 'Always unlucky in mingling',
    state: 'Any state',
    vision: 'Hardworking and independent',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Ngozichi',
    attitude: 'Proud and behaves unseemly',
    height: 'Average height',
    weight: 'slim',
    age: 'any age',
    status: 'marry on time always',
    state: 'any sate',
    vision: 'hopful and loving!',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Mgbodichi',
    attitude: 'Deceitful and unappologetic',
    height: 'Average height',
    weight: 'slim',
    age: 'above 30',
    status: 'always marry on time',
    state: 'any state',
    vision: 'Audacious',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Njoku',
    attitude: 'very realistic',
    height: 'Average height',
    weight: 'slim',
    age: 'any age',
    status: 'single',
    state: 'any state',
    vision: 'totally hopeful and could easily be disenchanted by peoples lifestyles.Lovely and accommodating',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Eke',
    attitude: 'Traditionalistic and honest',
    height: 'Good height',
    weight: 'slim',
    age: 'above 30',
    status: 'doesnt take the last postion',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Uju',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'fat',
    age: 'below 40',
    status: 'single',
    state: 'Abia',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Ogadimma',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'fat',
    age: 'below 30',
    status: 'single',
    state: 'imo',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Nwachi',
    attitude: 'Unpredictable and thoughtful',
    height: 'short sometimes',
    weight: 'Good body',
    age: 'above 20',
    status: 'No date, anything goes',
    state: 'Any state',
    vision: 'poised',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Mmaduka',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: '32',
    status: 'single',
    state: 'imo',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Uche',
    attitude: 'Jealouse and unrelenting',
    height: 'Normal height',
    weight: 'Good body',
    age: 'above 28',
    status: 'Unlucky in marriage',
    state: 'Any state',
    vision: 'Strong mindset and ardamant!',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Chigoziem',
    attitude: ' Smart and unpredictable',
    height: 'Good height',
    weight: 'fat',
    age: ' above 23',
    status: 'single',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Amaka',
    attitude: 'Ambitious and dangerous',
    height: 'Average height',
    weight: 'fat',
    age: '40',
    status: 'marrying always',
    state: 'Any state',
    vision: 'strong willed',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Chioma',
    attitude: 'full of Anger',
    height: 'Average height',
    weight: 'slim',
    age: '26',
    status: 'always alone but mingling and untiring!',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Ndidi',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'fat',
    age: '45',
    status: 'married but late',
    state: 'Any state',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Ekpereamaka',
    attitude: 'confused and undecided',
    height: 'tall in height',
    weight: 'fat',
    age: '25',
    status: 'can be dangerous mingling',
    state: 'Abia',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Chidimma',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: '37',
    status: 'always ready to mingle-no shame!',
    state: 'Anambra',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Chinyere',
    attitude: 'Alway positive',
    height: 'Good height',
    weight: 'fat',
    age: '38',
    status: 'always marry late',
    state: 'Anambra',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Ngozi',
    attitude: 'can be annoying sometimes',
    height: 'Average height',
    weight: 'normal',
    age: '30',
    status: 'always wishy',
    state: 'imo',
    vision: 'daring',
    sexuality: 'undecided',
    id: uuid.v4(),
},
{name: 'oluchi',
    attitude: 'unstable, liar and quiet',
    height: 'average height',
    weight: 'goood body',
    age: '39',
    status: 'Always ready to mingle',
    state: 'Ebonyi',
    vision: 'visionary',
    sexuality: 'normal',
    id: uuid.v4(),
},

{name: 'Nkem',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'slim',
    age: '35',
    status: 'not realistic about it',
    state: 'Enigu',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Odinaka',
    attitude: 'messy lifestyle',
    height: 'Average height',
    weight: 'fat',
    age: '20',
    status: 'single',
    state: 'Enugu',
    vision: 'hopeful',
    sexuality: 'gay',
    id: uuid.v4(),
},
{name: 'Ugochukwu',
    attitude: 'Alway positive',
    height: 'Average height',
    weight: 'fat',
    age: '30',
    status: 'undecided',
    state: 'Anambra',
    vision: 'poised',
    sexuality: 'straight',
    id: uuid.v4(),
},
{name: 'Nkeonye',
    attitude: 'very quiet and deceitful',
    height: 'Average height',
    weight: 'good body',
    age: '30',
    status: 'always single',
    state: 'imo',
    vision: 'visionary',
    sexuality: 'straight',
    id: uuid.v4(),
},
{   name: 'chukwuma',
    attitude: 'Always positive',
    height: 'short in height',
    weight: 'slim',
    age: 'below 60',
    status: 'married very late',
    state: 'Any state',
    vision: 'poised and hopeful',
    sexuality: 'straight',
    id: uuid.v4(),
},
{   "name" : "Ebere",
    "attitude": "'Always positive'",
    "height": "'Good height'",
    "weight": "'fat'",
    "age": 30,
    "status": "'married very late'",
    "state": "'Delta'",
    "vision": "'visionary'",
    "sexuality": "'straight'",
    "id": uuid.v4(),
}
]
   
module.exports = yourNames;
   